#!/bin/bash

# Definindo as variáveis de cores
white="\033[0m"
yellow="\033[1;33m"
green="\033[1;32m"
mag="\033[1;35m"
blue="\033[1;34m"
red="\033[1;31m"
cyano="\033[1;36m"
DIVIS="${white}//${yellow}//${green}//${mag}//"

# Função para verificar se a porta está disponível
check_port() {
    port=$1
    result=$(ss -tln | grep -w ":$port")
    if [ -z "$result" ]; then
        echo -e "${green}A porta $port está disponível.$white"
        available=true
    else
        echo -e "${red}A porta $port não está disponível.$white"
        read -p "Deseja trocar de porta? (s/n): " choice
        case "$choice" in
            s|S) available=false ;;
            n|N) available=true ;;
            *)
                echo -e "${yellow}Opção inválida. Por favor, escolha novamente.$white"
                check_port $port
            ;;
        esac
    fi
}

# Função para alterar a porta de um serviço
change_port() {
    local service=$1
    local config_file=$2
    local search=$3
    local port_label=$4

    echo -e "$DIVIS"
    echo -e "${white}Alterando porta para ${service}$white"
    echo -e "$DIVIS"

    while true; do
        read -p "Digite a nova porta para $service: " new_port
        if [[ $new_port =~ ^[0-9]+$ ]]; then
            check_port $new_port
            if [ "$available" = true ]; then
                sed -i "s/$search/$port_label$new_port/" $config_file
                echo -e "${green}Porta alterada para $new_port com sucesso!$white"
                break
            fi
        else
            echo -e "${red}Por favor, digite um número de porta válido.$white"
        fi
    done
}

# Menu de serviços
menu() {
    clear
    echo -e "$DIVIS"
    echo -e "${blue}--${yellow}>>${white} Menu${blue}/${yellow}PORTA CHANGER MENU${blue}/${mag}SERVIÇOS${white}"
    echo -e "$DIVIS"
    echo -e "${green}01${yellow} - ${white}STUNNEL4"
    echo -e "${green}02${yellow} - ${white}DROPBEAR"
    echo -e "${green}03${yellow} - ${white}MTPROTO"
    echo -e "${green}04${yellow} - ${white}TROJAN"
    echo -e "${green}05${yellow} - ${white}SSH"
    echo -e "${green}06${yellow} - ${white}OPENVPN"
    echo -e "${green}07${yellow} - ${white}SQUID PROXY"
    echo -e "${green}08${yellow} - ${white}BADVPN"
    echo -e "${green}09${yellow} - ${white}SSLH"
    echo -e "${green}00${yellow} - ${white}SAIR"
    echo -e "$DIVIS"

    read -p "Escolha o serviço para alterar a porta: " choice

    case $choice in
        v )  $mainmenu ;;
        01) change_port "STUNNEL4" "/etc/stunnel/stunnel.conf" "^accept = " "accept = " ;;
        02) change_port "DROPBEAR" "/etc/default/dropbear" "^DROPBEAR_PORT=" "DROPBEAR_PORT=" ;;
        03) change_port "MTPROTO" "/etc/mtproto-proxy.conf" "^PORT=" "PORT=" ;;
        04) change_port "TROJAN" "/etc/trojan/config.json" "\"local_port\": " "\"local_port\": " ;;
        05) change_port "SSH" "/etc/ssh/sshd_config" "^Port " "Port " ;;
        06) change_port "OPENVPN" "/etc/openvpn/server.conf" "^port " "port " ;;
        07) change_port "SQUID PROXY" "/etc/squid/squid.conf" "^http_port " "http_port " ;;
        08) change_port "BADVPN" "/etc/badvpn/tun2socks.conf" "^port=" "port=" ;;
        09) change_port "SSLH" "/etc/default/sslh" "^RUN=\"/usr/sbin/sslh" "RUN=\"/usr/sbin/sslh -p " ;;
        00) exit ;;
        *)
            echo -e "${red}Opção inválida!$white"
            sleep 2
            menu
        ;;
    esac
}

menu