#!/bin/bash

RDYBADVPN(){
    clear
    echo -e $DIVIS
    echo -e "${blue}--$yellow>>$f$white menu${blue}/${yellow}MENU DE INSTALAÇÃO${blue}/${mag}BADVPN$f                    $yellow [${blue}v$yellow] $yellow=$f$white Voltar$f";
    echo -e $DIVIS
    echo -e "$green ##### $white IP:$cyano  $ip $f";
    echo -e "$green ##### $white $SYSTEM:$cyano  $system_info $f";
    echo -e "$green ##### $white $USER:$cyano  $USERPROFILENAME $f";
    echo -e $DIVIS

    echo -e "${white}//${yellow}//${green}//${mag}//    ${yellow}INSTALADOR BADVPN$f"
    echo -e $DIVIS
    if [[ "$BADVPNSTATUS" = 'YES' ]]; then
        service="udpgw";
        if (( $(ps -ef | grep -v grep | grep $service | wc -l) > 0 ))
        then
            echo -ne "$green $yellow [${blue}p$yellow] $yellow=$f$white $STOPSERVICE $f"; echo -e "$BADVPNINFO";
        else
            echo -ne "$green $yellow [${blue}s$yellow] $yellow=$f$white $STARTSERVICE $f"; echo -e "$BADVPNINFO";
        fi
        echo -e $DIVIS
        echo -e "$green $yellow [${blue}01$yellow] $yellow=$f$white DESISTALAR BADVPN $f";
        echo -e "$green $yellow [${blue}00$yellow] $yellow=$f$white $EXIT $f";
        echo -e $DIVIS

        echo -ne "$yellow  Opção:$f";read -p ""  option

        case $option in

            v )  $mainmenu ;;
            p | P ) kill -9 $(ps -ef | grep badvpn | awk '{print $2}') > /dev/null 2> /dev/null & RDYSPINNER
                echo -e "${white}//${yellow}//${green}//${mag}//    ${red}(STOP) ${blue}OPERAÇÃO ${green}CONCLUÍDA!$f";
                echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar...$f"; read -n1 -r -p "";
            RDYBADVPN ;;
            s | S ) badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 > /dev/null & RDYSPINNER
                echo -e "${white}//${yellow}//${green}//${mag}//    ${red}(START) ${blue}OPERAÇÃO ${green}CONCLUÍDA!$f";
                echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar...$f"; read -n1 -r -p "";
            RDYBADVPN ;;
            1 | 01) echo -e "${white}//${yellow}//${green}//${mag}//    ${green} DESINSTALAR BADVPN?$f"; read -p "[s/n]: " -e -i n REMOVE
                if [[ "$REMOVE" = 's' ]]; then
                    echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}DESINSTALANDO, ${green}AGUARDE...$f";
                    kill -9 $(ps -ef | grep badvpn | awk '{print $2}') > /dev/null 2> /dev/null & RDYSPINNER
                    if [[ "$OS" = 'debian' ]]; then
                        apt-get remove --purge BADVPN -y 1> /dev/null 2> /dev/null & RDYSPINNER
                    else
                        yum remove BADVPN -y 1> /dev/null 2> /dev/null & RDYSPINNER
                    fi
                    echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}DESINSTALAÇÃO ${green}CONCLUÍDA!$f";
                    echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...$f"; read -n1 -r -p "";
                    $mainmenu
                else
                    echo "";
                    echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}OPERAÇÃO CANCELADA!\n$f";
                    echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...$f"; read -n1 -r -p "";
                    $mainmenu
                fi
            ;;
            00) exit ;;
            *)echo -e "$red Opção inválida!$f" ; echo "" ; sleep 2 ; $mainmenu;;
        esac
        elif [[ "$BADVPNSTATUS" = 'NO' ]]; then
        echo -e "$BADVPNINFO";
        echo -e $DIVIS
        echo -ne "${white}//${yellow}//${green}//${mag}//    ${yellow}CONTINUAR COM A CONFIGURAÇÃO DO BADVPN?$f"; read -p " [s/n]: " -e -i s yesNo
        echo -e $DIVIS


        if [[ "$yesNo" = 's' ]]; then
            echo -ne "${white}(${mag}<${green}i${mag}>${white})    ${blue}A porta 7300 já vem definida por padrão na configuração  BADVPN.$f";
            echo -e $DIVIS

            echo "";
            echo -e "${white}//${yellow}//${green}//${mag}//    ${mag}Pressione uma tecla para iniciar...$f"; read -n1 -r -p "";
            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}INICIANDO INSTALAÇÃO ${green}AGUARDE...$f";
            if [[ "$OS" = 'debian' ]]; then
                apt-get install -f -y > output.txt #1> /dev/null 2> /dev/null & RDYSPINNER
                dpkg --configure -a -y 1> /dev/null 2> /dev/null & RDYSPINNER
                apt-get update -y 1> /dev/null 2> /dev/null  & RDYSPINNER
                apt-get install -y gcc 1> /dev/null 2> /dev/null & RDYSPINNER
                apt-get install -y make 1> /dev/null 2> /dev/null & RDYSPINNER
                apt-get install -y g++ 1> /dev/null 2> /dev/null & RDYSPINNER
                apt-get install -y openssl 1> /dev/null 2> /dev/null & RDYSPINNER
                apt-get install -y build-essential 1> /dev/null 2> /dev/null & RDYSPINNER
                apt-get install -y cmake 1> /dev/null 2> /dev/null & RDYSPINNER
            else
                yum install -f -y 1> /dev/null 2> /dev/null & RDYSPINNER
                dpkg --configure -a -y 1> /dev/null 2> /dev/null & RDYSPINNER
                yum update -y 1> /dev/null 2> /dev/null  & RDYSPINNER
                yum install -y gcc 1> /dev/null 2> /dev/null & RDYSPINNER
                yum install -y make 1> /dev/null 2> /dev/null & RDYSPINNER
                yum install -y g++ 1> /dev/null 2> /dev/null & RDYSPINNER
                yum install -y openssl 1> /dev/null 2> /dev/null & RDYSPINNER
                yum install -y build-essential 1> /dev/null 2> /dev/null & RDYSPINNER
                yum install -y cmake 1> /dev/null 2> /dev/null & RDYSPINNER
            fi

            # if aki
            wget - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 -o 1> /dev/null 2> /dev/null & RDYSPINNER
            tar -xf badvpn-1.999.128.tar.bz2 1> /dev/null 2> /dev/null & RDYSPINNER
            mkdir /etc/badvpn-install 1> /dev/null 2> /dev/null & RDYSPINNER
            cd /etc/badvpn-install 1> /dev/null 2> /dev/null & RDYSPINNER
            cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 1> /dev/null 2> /dev/null & RDYSPINNER
            make install 1> /dev/null 2> /dev/null & RDYSPINNER
            rm -rf /etc/badvpn-install 1> /dev/null 2> /dev/null & RDYSPINNER
            cd ; rm -rf badvpn.sh badvpn-1.999.128/ badvpn-1.999.128.tar.bz2 1> /dev/null 2> /dev/null & RDYSPINNER
            echo -e "${green} Executando em screem (Aguarde 5 segundos...)$f";
            sleep 5
            screen -dm badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 #> /dev/null & RDYSPINNER
            #else
            #######
            #echo -e "${red}OPS! HÁ ALGO DE ERRADO!\n${mag}Favor entrar em contato com seu fornecedor! ${mag}(BADVPN CONFIG RUNNING)$f";
            #echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...$f"; read -n1 -r -p "";
            #$mainmenu
            #fi
            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}CONFIGURAÇÃO CONCLUÍDA COM ${green}SUCESSO!$f";
            echo "";
            echo -e "${white}//${yellow}//${green}//${mag}//    ${green} √ ${white} PORTA BADVPN:${red} 7300 $f"
            echo ""
            echo -e $DIVIS
            echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...$f"; read -n1 -r -p "";
            $mainmenu
            elif [[ "$yesNo" = 'n' ]]; then
            echo -e $DIVIS

            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}OPERAÇÃO CANCELADA!\n${green}Pressione uma tecla para retornar ao menu inicial...$f"; read -n1 -r -p "";
            echo -e $DIVIS

            $mainmenu
            elif [[ "$yesNo" = 'v' ]]; then
            $mainmenu
        else
            echo -e "${white}//${yellow}//${green}//${mag}//    ${blue}OPÇÃO INVÁLIDA!$f";
            echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...$f"; read -n1 -r -p "";
            $mainmenu
        fi
    else
        echo -e "${white}//${yellow}//${green}//${mag}//    ${red}OPS! HÁ ALGO DE ERRADO!\n${mag}Favor entrar em contato com seu fornecedor! ${mag}(BADVPN)$f";
        echo -ne "${white}//${yellow}//${green}//${mag}//    ${green}Pressione uma tecla para retornar ao menu inicial...$f"; read -n1 -r -p "";
        $mainmenu
    fi
}